"""empty message

Revision ID: 1b18ed523f10
Revises: 397cba89d209
Create Date: 2018-03-16 21:29:15.678553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b18ed523f10'
down_revision = '397cba89d209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'user_profile_username_key', 'user_profile', type_='unique')
    op.drop_column('user_profile', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'user_profile_username_key', 'user_profile', ['username'])
    # ### end Alembic commands ###
