"""empty message

Revision ID: 5bc34f0f2d53
Revises: 1bb28bade74a
Create Date: 2018-03-17 02:30:51.212299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc34f0f2d53'
down_revision = '1bb28bade74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('bio', sa.String(length=255), nullable=True))
    op.drop_column('user_profile', 'biography')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('biography', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user_profile', 'bio')
    # ### end Alembic commands ###
