"""empty message

Revision ID: fa9407c9b606
Revises: 5bc34f0f2d53
Create Date: 2018-03-22 03:31:51.423507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9407c9b606'
down_revision = '5bc34f0f2d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('email', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'email')
    # ### end Alembic commands ###
